### PR TITLE
Fix typo in Android permission documentation

### PR DESCRIPTION
**Pull request by juliusmh**
Fix typo in android permission (COARSE_LOCATION)

### CODE REVIEW

**Review by twyatt — APPROVED** [review]
Thanks for catching/fixing this!

**Comment by juliusmh** [comment]
> Thanks for catching/fixing this!

Any clue why the CI is failing on a docs change?

**Comment by twyatt** [comment]
A misconfiguration on my part.
It should skip that CI step for external contributions.
I plan to fix it, but I'll merge manually until then.

**Comment by twyatt** [comment]
> > Thanks for catching/fixing this!
> 
> Any clue why the CI is failing on a docs change?

See #529 for details (should be fixed by #530).

**Comment by twyatt** [comment]
Thanks again @juliusmh for the contribution!

**Comment by juliusmh** [comment]
> Thanks again @juliusmh for the contribution!

It's just a typo. I hope I can contribute some more interesting code soon.

**Pull request merged**
