### PR TITLE
Use `Uuid` from Kotlin standard library

### LINKED ISSUE #748: Use `Uuid` from Kotlin standard library

### PR DESCRIPTION
**Pull request by ykws**
Hi @twyatt
Although it may already be in progress, I tried switching to Kotlin UUID.

https://kotlinlang.org/docs/whatsnew2020.html#standard-library

- fixes #748

I have modified it so that only one `@OptIn(ExperimentalUuidApi::class)` annotation is needed for the file.
Please let me know any feedback.

### CODE REVIEW

**Comment by twyatt** [comment]
Awesome, thanks for this!
I'll want to wait to get this in not the next release, but the release after that.
So, you may have to do some rebasing and/or conflict resolution, apologies for that.
I'll keep you posted though.

**Comment by ykws** [comment]
@twyatt Thank you. I’ll leave it to you. I encountered [some errors](https://github.com/JuulLabs/kable/actions/runs/10969172631/job/30461586358) and did a force push. The CI is now showing as “Action required.” Could you please rerun it?

https://github.com/JuulLabs/kable/actions/runs/10969254146

**Comment by ykws** [comment]
I will check the following error.

> Task :kable-core:androidApiCheck FAILED

The type of UUID might have unintentionally changed Java to Kotlin.

**Comment by twyatt** [comment]
Run `./gradlew apiDump` and then push changes.

**Review by cedrickcooke — APPROVED** [review]

**Comment by twyatt** [comment]
@ykws when you have a chance, can you rebase this onto the latest `main`?

**Comment by ykws** [comment]
@twyatt Thank you for keeping me informed. Merged the main branch and fixed the build. CI passed successfully. Please review again.

**Comment by twyatt** [comment]
Pretty busy on another project at the moment, but will review soon.

**Review by twyatt — APPROVED** [review]
Great job and thank you!

**Comment by twyatt** [comment]
I will integrate/test this with [SensorTag sample app](https://github.com/JuulLabs/sensortag) then merge soon.

**Comment by twyatt** [comment]
Quick update: some issues with `0.35.0-rc` were reported. I'd like to get those resolved and release `0.35.0-rc2` before merging these changes. This PR will get merged in due time, thanks for being patient!

**Comment by twyatt** [comment]
Thanks for the contribution, @ykws!
I'll try to get to the remaining issues in the [0.36.0 milestone](https://github.com/JuulLabs/kable/milestone/54) soon, then get a release out with these UUID changes.

**Pull request merged**
