### PR TITLE
Return device name from the scan record when available on Android

### PR DESCRIPTION
**Pull request by L3K0V**
TLDR: Check and return device name from the advertisement scan record if available. If not return device name as before.

[As I wrote in the discussions](https://github.com/JuulLabs/kable/discussions/400) I had some issues with iBeacon devices. I noticed that on Apple devices I got more advertisements having names than the Android results. I start digging a bit and investigating and stumble upon this:
https://stackoverflow.com/questions/26290640/android-bluetoothdevice-getname-return-null and more especially:

> Advertisement data is how a client BTLE endpoint discovers a service device. A client can request a scan response and get more data. The device name is optional in this data. However, the BTLE spec requires that all Bluetooth Low Energy endpoints support the Generic Access service which is required to support the Device Name characteristic.
> ...
> Fortunately, most BTLE devices I have worked with do provide their name in the advertisement or scan response.
>
> Another possibility is that the device may place the name in the scan response part of the advertisement....

And

> On Marshmallow, utilize `ScanRecord.getDeviceName()` to retrieve the local name embedded in the scan record.
>
> `BluetoothDevice.getName()` is unreliable if the local name is included in a scan response, rather than in the immediate advertising packet.

### CODE REVIEW

**Review by cedrickcooke — APPROVED** [review]

**Comment by twyatt** [comment]
@L3K0V this looks like a good change, my only concern is if there are circumstances where `scanResult.scanRecord?.deviceName` value differs from `bluetoothDevice.name`? As this change could break library consumers if they were relying on a specific name (as returned by `bluetoothDevice.name`).

Normally I'd recommend that we'd deprecate the current property (and offer a new property), so that we can warn library consumers (via the deprecation) that the value may differ from prior versions, but:

- I'd imagine they should always be the same, or at least `scanResult.scanRecord?.deviceName` might hold a value when `bluetoothDevice.name` is `null`? — so, it'd be unlikely consumers would have a problem with `Advertisement.name` suddenly returning a non-`null` value
- Kable is still pre 1.0.0, so hopefully consumers understand that APIs could change/break with each version (as much as I'd like to avoid that)

...so, I think this is fine; but if you happen to know of instances where `scanResult.scanRecord?.deviceName` and `bluetoothDevice.name` might both hold a non-`null` value (but be different) then we should maybe consider a deprecation path for this.

**Comment by L3K0V** [comment]
Hey @twyatt,

> I'd imagine they should always be the same, or at least scanResult.scanRecord?.deviceName might hold a value when bluetoothDevice.name is null? — so, it'd be unlikely consumers would have a problem with Advertisement.name suddenly returning a non-null value

Correct.

> but if you happen to know of instances where `scanResult.scanRecord?.deviceName` and `bluetoothDevice.name` might both hold a non-null value (but be different) then we should maybe consider a deprecation path for this.

From what I know on Android via Settings user can change the Bluetooth device name (`bluetoothDevice.name`) which again can broke some Kable consumers, but the name represented in the `scanRecord` is controlled by the manufacturer and the firmware. Notice that in my case if I factory reset the bluetooth device the `scanRecord` name will be changed, as it's suffixed with an unique ID.

Also in my example looks that `bluetoothDevice.name` returns `null` on Android  but in nRF Connect tool they show the `scanRecord` name. Right now I'm not able to filter via Kable - it's working on iOS but not on Android. On iOS in all cases I have the device name.

**Review by twyatt — APPROVED** [review]

**Comment by L3K0V** [comment]
@twyatt btw, any deprecation path defined for this? I mean how we proceed with this?

**Comment by BluestormDNA** [comment]
@twyatt 
I saw this issue very late, but this was already reported on https://github.com/JuulLabs/kable/issues/143 (Android / iOS) and https://github.com/JuulLabs/kable/issues/156 (iOS)
And as said there I think it would be more reasonable to have both properties exposed. The cached name and the current advertised name.

Remember that them can and will be different (see https://github.com/JuulLabs/kable/issues/143) example on a device that changes name every 24h.
And users can rely on both of them depending on use cases. Fusing them together it's not a solution.

Exposing both of them would cover all the bases and @L3K0V could have his use case covered with something like:
`advertisedName ?: cachedName`

**Comment by twyatt** [comment]
Thanks @BluestormDNA for catching that and linking to the existing issues. I'll change to expose as two separate properties. 💯

**Comment by L3K0V** [comment]
Many thanks for the new information here @BluestormDNA much appreciated as I was trying to think about other use cases.

So after all @twyatt looks like it will be needed to expose both names, I can help here.

First - Is there similar problem on iOS? Shall we expose a common field or Android only field?
And I wonder how to explain to the users which one to use and when. I was thinking that `scanRecord` name is more likely to be the single source of truth.

I like having `advertisedName` and `localDeviceName`. Can be call the cached name local like local for the device?

**Pull request merged**
