### PR TITLE
Bump Kotlin to 1.6.0 and use hierarchical project structure

### PR DESCRIPTION
**Pull request by twyatt**
Related to #52.

Configures project to leverage [hierarchical project structure](https://kotlinlang.org/docs/reference/mpp-share-on-platforms.html) for iOS targets (and share code with MacOS target):

```
common 
|-- js 
|-- android 
'-- apple 
    |-- ios 
    '-- macos 
```

Requires Mac OS X 11 to build due to bumping Kotlin to 1.6.x.
Took the opportunity to bump all dependencies.

Advertisement unit tests were reworked to no longer instantiate `CBPeripheral` objects, as it was causing tests to crash:

<details>
<summary>Crash</summary>

```
> Failed to execute all tests:
  :core:iosX64Test: Test running process exited unexpectedly.
  Current test: connectingObserves_isAtLeast_connected_is_false
  Process output:
   2021-11-18 20:50:19.305 test.kexe[5528:24463] *** Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <CBPeripheral 0x6000024fc580> for the key path "delegate" from <CBPeripheral 0x6000024fc580> because it is not registered as an observer.'
  *** First throw call stack:
  (
  	0   CoreFoundation                      0x00000001056d2bb4 __exceptionPreprocess + 242
  	1   libobjc.A.dylib                     0x0000000105147be7 objc_exception_throw + 48
  	2   Foundation                          0x0000000105f27062 -[NSObject(NSKeyValueObserverRegistration) _removeObserver:forProperty:] + 689
  	3   Foundation                          0x0000000105f274c2 -[NSObject(NSKeyValueObserverRegistration) removeObserver:forKeyPath:] + 129
  	4   CoreBluetooth                       0x00000001054ded69 -[CBPeripheral dealloc] + 41
  	5   libobjc.A.dylib                     0x00000001051459f7 _ZN11objc_object17sidetable_releaseEbb + 177
  	6   test.kexe                           0x000000010495f43a -[NSObject(NSObjectToKotlin) releaseAsAssociatedObject:] + 26
  	7   test.kexe                           0x0000000104b6f6c2 Kotlin_ObjCExport_detachAndReleaseAssociatedObject + 82
  	8   test.kexe                           0x0000000104b39ab6 _ZN9ObjHeader17destroyMetaObjectEPS_ + 118
  	9   test.kexe                           0x0000000104b6b9ea _ZN6kotlin13RunFinalizersEP9ObjHeader + 138
  	10  test.kexe                           0x0000000104b432af _ZN12_GLOBAL__N_113freeContainerEP15ContainerHeader + 2127
  	11  test.kexe                           0x0000000104b3e2b7 _ZN12_GLOBAL__N_111decrementRCEP15ContainerHeader + 247
  	12  test.kexe                           0x0000000104b3a4b0 _ZN12_GLOBAL__N_114garbageCollectEP11MemoryStateb + 1248
  	13  test.kexe                           0x0000000104b46ee9 AllocArrayInstanceStrict + 457
  	14  test.kexe                           0x0000000104967e38 kfun:kotlin.collections#copyOfUninitializedElements__at__kotlin.CharArray(kotlin.Int;kotlin.Int){}kotlin.CharArray + 488
  	15  test.kexe                           0x000000010496858f kfun:kotlin.collections#copyOfUninitializedElements__at__kotlin.CharArray(kotlin.Int){}kotlin.CharArray + 175
  	16  test.kexe                           0x00000001049666fd kfun:kotlin.collections#copyOf__at__kotlin.CharArray(kotlin.Int){}kotlin.CharArray + 173
  	17  test.kexe                           0x00000001049e43c3 kfun:kotlin.text.StringBuilder#ensureCapacity(kotlin.Int){} + 419
  	18  test.kexe                           0x00000001049e5403 kfun:kotlin.text.StringBuilder.ensureExtraCapacity#internal + 99
  	19  test.kexe                           0x00000001049e40f0 kfun:kotlin.text.StringBuilder#append(kotlin.String?){}kotlin.text.StringBuilder + 368
  	20  test.kexe                           0x00000001049e3f0a kfun:kotlin.text.StringBuilder#append(kotlin.String){}kotlin.text.StringBuilder + 202
  	21  test.kexe                           0x00000001049bad90 kfun:kotlin.native.internal.test.TeamCityLogger.finish#internal + 656
  	22  test.kexe                           0x00000001049bc21d kfun:kotlin.native.internal.test.TeamCityLogger#pass(kotlin.native.internal.test.TestCase;kotlin.Long){} + 109
  	23  test.kexe                           0x00000001049c6c5d kfun:kotlin.native.internal.test.TestRunner.run#internal + 5725
  	24  test.kexe                           0x00000001049c9439 kfun:kotlin.native.internal.test.TestRunner.runIteration#internal + 4633
  	25  test.kexe                           0x00000001049ca622 kfun:kotlin.native.internal.test.TestRunner#run(){}kotlin.Int + 1410
  	26  test.kexe                           0x00000001049ba198 kfun:kotlin.native.internal.test#testLauncherEntryPoint(kotlin.Array<kotlin.String>){}kotlin.Int + 312
  	27  test.kexe                           0x00000001049ba28c kfun:kotlin.native.internal.test#main(kotlin.Array<kotlin.String>){} + 60
  	28  test.kexe                           0x0000000104959799 Konan_start + 153
  	29  test.kexe                           0x000000010495fcce Init_and_run_start + 94
  	30  dyld                                0x0000000104ed1e1e start_sim + 10
  	31  ???                                 0x0000000000000001 0x0 + 1
  )
  libc++abi: terminating with uncaught exception of type NSException
  Child process terminated with signal 6: Abort trap
```
</details>

### CODE REVIEW

**Comment by twyatt** [comment]
Great article outlining the pros/cons of various MPP sourceset configurations: https://medium.com/icerock/enable-iosmain-sourceset-in-kotlin-multiplatform-mobile-projects-91168db9ac5c

**Comment by twyatt** [comment]
This PR is blocked by upstream hierarchical multiplatform (HMPP) support.

Details can be found in:
- https://github.com/touchlab/Stately/issues/46
- https://github.com/cashapp/sqldelight/issues/1992

**Comment by twyatt** [comment]
Document to review once this effort is re-attempted: https://kotlinlang.org/docs/migrating-multiplatform-project-to-14.html#migrate-to-the-hierarchical-project-structure

**Comment by twyatt** [comment]
Note to self: add test source sets in gradle. Bump Kotlin version to non-RC.

**Review by cedrickcooke — APPROVED** [review]

**Comment by twyatt** [comment]
Converted to **draft** while I try to determine cause of crash on MacOS unit test.

**Review by sdonn3 — APPROVED** [review]

**Pull request merged**
