### PR TITLE
Add bluetooth status flow for Android and IOS

### PR DESCRIPTION
**Pull request by burnhamd**
References issue #288.  Implements a bluetooth status flow which exposes the status of the CBCentral in IOS and on Android the BluetoothAdapter.  We have added this for our project so that we know the current status reported by the delegate being used by the CentralManager.default we have created with kable library.

I am still not sure how this should be handled in JS.  Im not super familiar with WebBluetooth but it seems that these types of statuses are not available.  There is a method getAvailability, but this could result in a state that is not accurate so it seems in JS there is a bit of try and see with bluetooth permissions since the browser automatically requests permissions anyway.

Also I realize that there are numerous places that we are checking the status.  They could be refactored to use this, but for now I wanted to check the approach before changing how it is handled in peripherals.

### CODE REVIEW

**Comment by davidtaylor-juul** [comment]
I have some code snippets for Web BLE around this that may be useful to you here:
https://gist.github.com/davidtaylor-juul/3856335418e69b312899b416e9295130

The `availabilitychanged` event is experimental and not broadly supported but is really all we have in Web BLE right now.

**Comment by twyatt** [comment]
Sorry, got buried with other work tasks; I will try to look over this soon.

**Comment by twyatt** [comment]
@burnhamd I've created #335 (that was heavily inspired by this PR), it takes on a slightly different different API shape for the purposes of being able to provide support across all supported platforms.

Let me know what you think, and if it would fit your needs.

**Comment by twyatt** [comment]
Superseded by #335.
Thanks @burnhamd for kicking off this effort (#335 was heavily inspired by your work in this PR). ❤️

**Pull request closed without merging**
