### PR TITLE
Use shared bluetooth state `BroadcastReceiver`

### LINKED ISSUE #359: Too many receivers, total of 1000
In the context of my app I need to retrieve the peripheral in order to get the identifier.

The problem is that, on Android, it [registers a broadcast receiver](https://github.com/JuulLabs/kable/blob/main/core/src/androidMain/kotlin/Peripheral.kt#L137) every time and I quickly reach the limit of 1000 receivers which is prohibited by the OS.

I open this issue to discuss about ways to solve the problem in order to contribute by a pull request soon.

I suggest to share one broadcast receiver across all peripherals.

As a possible workaround, I will try to cancel the attached coroutine scope in order to [unregister the receiver](https://github.com/JuulLabs/kable/blob/main/core/src/androidMain/kotlin/Peripheral.kt#L146).

### PR DESCRIPTION
**Pull request by twyatt**
Closes #359

### CODE REVIEW

**Comment by nverinaud** [comment]
I confirm this fixes #359 !

**Review by cedrickcooke — APPROVED** [review]

**Review by sdonn3 — APPROVED** [review]

**Comment by dzgeorgy** [comment]
Shouldn't there be `awaitClose` call in callbackFlow?

**Comment by twyatt** [comment]
> Shouldn't there be `awaitClose` call in callbackFlow?

Yikes, I think you're right. Oversight on my part.

**Comment by twyatt** [comment]
Thanks @dzgeorgy, confirmed that `awaitClose` definitely should've been used.
Fixed in #399.

**Pull request merged**
