### PR TITLE
Add property for retrieving raw bytes of scan record

### PR DESCRIPTION
**Pull request by kemalfaust**
adding scan record byte support,
https://github.com/JuulLabs/kable/issues/356

### CODE REVIEW

**Review by twyatt — APPROVED** [review]

**Comment by twyatt** [comment]
@kemalfaust you'll need to run:

```
./gradlew apiDump
```

And commit the changes.

**Comment by kemalfaust** [comment]
@twyatt sorry my first pull request, I think now its ready

**Comment by twyatt** [comment]
Look like your API dump is for an outdated commit.
Try going a `git pull` and then running the `./gradlew apiDump` again?

**Comment by twyatt** [comment]
@kemalfaust everything looks good, I'll merge (and release) shortly after I get another review approval.

**Comment by kemalfaust** [comment]
Nice, thank you @twyatt I'll wait new Release 🎉

**Review by davidtaylor-juul — APPROVED** [review]

**Pull request merged**
